### ISSUE TITLE
link to migrate does not work + migrate part of the docs not present

### ISSUE THREAD

**Issue by honzakutil** [markh-de/KiVar#63]
**Describe the bug**
I installed KiVar 0.2.0-dev32 and run it with the board file, which already contains some KiVar rules. KiVar reported, that it does not find any valid rules, but it found 140 legacy rules and offers me a link `https://help.kivar.markh.de#migrate`. Links directed me to the `readme.md` from the kivar repo, but there is no part about the migration written yet.

I want to convert KiVar rules from the legacy to the new format on that board, so the migration part of the documentation will be handy. If it will be ready soon, I can use it (=test it for you). Otherwise, I will do the conversion on my own and I will write here some notes about it, so you can use the notes when creating the migration section of the documentation. 

Do you have some guess, when the migration part of the documentation will be ready, so I could decide whether I will wait for it or not?

**Comment by markh-de** [comment]
Actually, there already is a migration guide on an extra documentation branch.  It's just that the link (redirection) was not ready yet.  It should be now.  The redirection was a 301 (permanent) before (it's a 302 (temporary) now), so your browser may need to reload the link.  Here's the direct link, in case you still get a cached link target:

https://github.com/markh-de/KiVar/blob/46-update-documentation-for-020-release/README.md#migrate

I hope the guide is sufficiently complete.  If you have any problems understanding the changes, please open a new issue and post your questions.  We can collect migration questions there, so that the docs can be fixed.

Thanks for your patience.  I really have very few spare time to work on the project.
